### ISSUE TITLE
rainfall query returning crop attributes

### ISSUE THREAD

**Issue by davelandry** [Datawheel/data-africa-api#1]
looks like some wires are getting crossed?
`/api/join/?show=geo&geo=040AF00182&required=rainfall_awa_mm,year`

**Comment by jspeis** [comment]
What happening here is that `rainfall_awa_mm` doesn't have a year value so the API is trying to join the year from another table. I will add a two year columns to this table (its a span of years not a single year) to the table but for now it should work if you leave out the year variable
