### ISSUE TITLE
poverty query chokes with year=latest

### ISSUE THREAD

**Issue by davelandry** [Datawheel/data-africa-api#2]
`/api/join/?show=geo&geo=040AF00182&required=hc&poverty_level=ppp1&year=latest`

**Comment by jspeis** [comment]
I'll fix this. In the meantime the work around is to use the following syntax:

`/api/join/?show=year,geo&geo=040AF00182&required=hc&poverty_level=ppp1&sumlevel=latest_by_geo,all`

**Comment by jspeis** [comment]
Actually turns out that is not just the workaround, but the actual solution is this case. This is because year=latest will compute the overall latest year from the table, whereas the latest_by_geo sumlevel will give you the latest year for the given geography which is what you want.
